config/routes.rb
# Jozu Gantt Plugin - routes.rb
#
# The MIT License (MIT)
#
# Copyright (c) [2016] [jozuko]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get '/jozu_gantt' => 'jozu_gantt_settings#index'
get '/projects/:project_id/jozu_gantt' => 'jozu_gantt_settings#project_index'

Rails.application.routes.draw do
  match 'jozu_gantt_settings/:action', :controller => 'jozu_gantt_settings', :via => [:get, :post, :patch, :put]
  match 'projects/:project_id/jozu_gantt_settings/:action', :controller => 'jozu_gantt_settings', :via => [:get, :post, :patch, :put]

  match 'projects/:project_id/issues/jozu_gantt/context_menu', :to => 'jozu_gantt#context_menu', :via => [:get, :post]
  match 'projects/:project_id/jozu_gantt/:action', :controller => 'jozu_gantt', :via => [:get, :post, :patch, :put]
end

app/controllers/jozu_gantt_controller.rb
# encoding: utf-8
#
# Jozu Gantt Plugin - JozuGanttController
#
# The MIT License (MIT)
#
# Copyright (c) [2016] [jozuko]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
class JozuGanttController < ApplicationController
  unloadable

  helper :watchers
  helper :issues

  include Redmine::Utils::DateCalculation

  before_filter :find_project
  before_filter :find_issues, :only => [:context_menu, :issue_edit]

  # 関連付けを担当者でやり直し
  def associate

    # 関連付けを削除
    beforeIssueRelationIds = relation_ids
    IssueRelation.delete_all(id: beforeIssueRelationIds)

    # 担当者ごとに関連付けを設定
    @project.members.each do |member|
      issues = Issue.find_by_sql(["select id, start_date, due_date from issues where assigned_to_id=:assigned_to_id and project_id=:project_id order by start_date, due_date, id", {:assigned_to_id => member.user_id, :project_id => @project.id}])
      if issues.present?
        issues.each_with_index do |issue, index|
          if index == 0
            next
          end

          begin
            delay = 0

            if issues[index].start_date > issues[index-1].due_date
              delay = working_days(issues[index-1].due_date, issues[index].start_date) - 2
            else
              delay = working_days(issues[index].start_date, issues[index-1].due_date) * -1
            end

            relation = IssueRelation.new
            relation.issue_from_id = issues[index-1].id
            relation.issue_to_id   = issues[index].id
            relation.delay         = delay
            relation.relation_type = "precedes"
            relation.save!
          rescue
          end
        end
      end
    end

    # ガントチャート画面にリダイレクト
    redirect_to :controller => 'gantts',
                :action => 'show',
                :project_id => @project
  end

  # 関連付けすべて削除
  def delete_relation

    # 関連付けを削除
    beforeIssueRelationIds = relation_ids
    IssueRelation.delete_all(id: beforeIssueRelationIds)

    # ガントチャート画面にリダイレクト
    redirect_to :controller => 'gantts',
                :action => 'show',
                :project_id => @project
  end

  # プロジェクトに設定されているすべての関連付けを取得
  def relation_ids
    return IssueRelation.find_by_sql(["select issue_relations.id from issue_relations inner join issues on issues.project_id=:project_id and (issue_relations.issue_from_id=issues.id or issue_relations.issue_to_id=issues.id)", {:project_id => @project.id}]);
  end

  # context_menu
  def context_menu
    if (@issues.size == 1)
      @issue = @issues.first
    end
    @issue_ids = @issues.map(&:id).sort

    @allowed_statuses = @issues.map(&:new_statuses_allowed_to).reduce(:&)

    @can = {:edit => User.current.allowed_to?(:edit_issues, @projects),
            :log_time => (@project && User.current.allowed_to?(:log_time, @project)),
            :copy => User.current.allowed_to?(:copy_issues, @projects) && Issue.allowed_target_projects.any?,
            :delete => User.current.allowed_to?(:delete_issues, @projects)
            }
    if @project
      if @issue
        @assignables = @issue.assignable_users
      else
        @assignables = @project.assignable_users
      end
      @trackers = @project.trackers
    else
      #when multiple projects, we only keep the intersection of each set
      @assignables = @projects.map(&:assignable_users).reduce(:&)
      @trackers = @projects.map(&:trackers).reduce(:&)
    end
    @versions = @projects.map {|p| p.shared_versions.open}.reduce(:&)

    @priorities = IssuePriority.active.reverse
    @back = back_url

    @options_by_custom_field = {}
    if @can[:edit]
      custom_fields = @issues.map(&:editable_custom_fields).reduce(:&).reject(&:multiple?)
      custom_fields.each do |field|
        values = field.possible_values_options(@projects)
        if values.present?
          @options_by_custom_field[field] = values
        end
      end
    end

    @safe_attributes = @issues.map(&:safe_attribute_names).reduce(:&)
    render :layout => false
  end

  def logger
    ::Rails.logger
  end

  # before filter
  def find_project
    if params[:project_id].present?
      @project = Project.find_by(identifier: params[:project_id])
    end
  end
end

app/helpers/jozu_gantt_helper.rb
# encoding: utf-8
#
# Jozu Gantt Plugin - JozuGanttHelper
#
# The MIT License (MIT)
#
# Copyright (c) [2016] [jozuko]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
module JozuGanttHelper

  def context_menu_link(name, url, options={})
    options[:class] ||= ''
    if options.delete(:selected)
      options[:class] << ' icon-checked disabled'
      options[:disabled] = true
    end
    if options.delete(:disabled)
      options.delete(:method)
      options.delete(:data)
      options[:onclick] = 'return false;'
      options[:class] << ' disabled'
      url = '#'
    end
    link_to h(name), url, options
  end

end

app/views/jozu_gantt/context_menu.html.erb
<% include_calendar_headers_tags %>

<ul>
  <%= call_hook(:view_issues_context_menu_start, {:issues => @issues, :can => @can, :back => @back }) %>

  <% if @issue -%>
    <li><%= context_menu_link l(:button_edit), edit_issue_path(@issue),
            :class => 'icon-edit', :disabled => !@can[:edit] %></li>
  <% else %>
    <li><%= context_menu_link l(:button_edit), bulk_edit_issues_path(:ids => @issue_ids),
            :class => 'icon-edit', :disabled => !@can[:edit] %></li>
  <% end %>

  <% if @allowed_statuses.present? %>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_status) %></a>
    <ul>
    <% @allowed_statuses.each do |s| -%>
        <li><%= context_menu_link s.name, bulk_update_issues_path(:ids => @issue_ids, :issue => {:status_id => s}, :back_url => @back), :method => :post,
                                  :selected => (@issue && s == @issue.status), :disabled => !@can[:edit] %></li>
    <% end -%>
    </ul>
  </li>
  <% end %>

  <% if @trackers.present? %>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_tracker) %></a>
    <ul>
    <% @trackers.each do |t| -%>
        <li><%= context_menu_link t.name, bulk_update_issues_path(:ids => @issue_ids, :issue => {'tracker_id' => t}, :back_url => @back), :method => :post,
                                  :selected => (@issue && t == @issue.tracker), :disabled => !@can[:edit] %></li>
    <% end -%>
    </ul>
  </li>
  <% end %>

  <% if @safe_attributes.include?('priority_id') && @priorities.present? -%>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_priority) %></a>
    <ul>
    <% @priorities.each do |p| -%>
        <li><%= context_menu_link p.name, bulk_update_issues_path(:ids => @issue_ids, :issue => {'priority_id' => p}, :back_url => @back), :method => :post,
                                  :selected => (@issue && p == @issue.priority), :disabled => (!@can[:edit] || @issues.detect {|i| !i.leaf?}) %></li>
    <% end -%>
    </ul>
  </li>
  <% end %>

  <% if @safe_attributes.include?('fixed_version_id') && @versions.present? -%>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_fixed_version) %></a>
    <ul>
    <% @versions.sort.each do |v| -%>
        <li><%= context_menu_link format_version_name(v), bulk_update_issues_path(:ids => @issue_ids, :issue => {'fixed_version_id' => v}, :back_url => @back), :method => :post,
                                  :selected => (@issue && v == @issue.fixed_version), :disabled => !@can[:edit] %></li>
    <% end -%>
        <li><%= context_menu_link l(:label_none), bulk_update_issues_path(:ids => @issue_ids, :issue => {'fixed_version_id' => 'none'}, :back_url => @back), :method => :post,
                                  :selected => (@issue && @issue.fixed_version.nil?), :disabled => !@can[:edit] %></li>
    </ul>
  </li>
  <% end %>

  <% if @safe_attributes.include?('assigned_to_id') && @assignables.present? -%>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_assigned_to) %></a>
    <ul>
    <% if @assignables.include?(User.current) %>
        <li><%= context_menu_link "<< #{l(:label_me)} >>", bulk_update_issues_path(:ids => @issue_ids, :issue => {'assigned_to_id' => User.current}, :back_url => @back), :method => :post,
                                  :disabled => !@can[:edit] %></li>
    <% end %>
    <% @assignables.each do |u| -%>
        <li><%= context_menu_link u.name, bulk_update_issues_path(:ids => @issue_ids, :issue => {'assigned_to_id' => u}, :back_url => @back), :method => :post,
                                  :selected => (@issue && u == @issue.assigned_to), :disabled => !@can[:edit] %></li>
    <% end -%>
        <li><%= context_menu_link l(:label_nobody), bulk_update_issues_path(:ids => @issue_ids, :issue => {'assigned_to_id' => 'none'}, :back_url => @back), :method => :post,
                                  :selected => (@issue && @issue.assigned_to.nil?), :disabled => !@can[:edit] %></li>
    </ul>
  </li>
  <% end %>

  <% if @safe_attributes.include?('category_id') && @project && @project.issue_categories.any? -%>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_category) %></a>
    <ul>
    <% @project.issue_categories.each do |u| -%>
        <li><%= context_menu_link u.name, bulk_update_issues_path(:ids => @issue_ids, :issue => {'category_id' => u}, :back_url => @back), :method => :post,
                                  :selected => (@issue && u == @issue.category), :disabled => !@can[:edit] %></li>
    <% end -%>
        <li><%= context_menu_link l(:label_none), bulk_update_issues_path(:ids => @issue_ids, :issue => {'category_id' => 'none'}, :back_url => @back), :method => :post,
                                  :selected => (@issue && @issue.category.nil?), :disabled => !@can[:edit] %></li>
    </ul>
  </li>
  <% end -%>

  <% if @safe_attributes.include?('done_ratio') && Issue.use_field_for_done_ratio? %>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_done_ratio) %></a>
    <ul>
    <% (0..10).map{|x|x*10}.each do |p| -%>
        <li><%= context_menu_link "#{p}%", bulk_update_issues_path(:ids => @issue_ids, :issue => {'done_ratio' => p}, :back_url => @back), :method => :post,
                                      :selected => (@issue && p == @issue.done_ratio), :disabled => (!@can[:edit] || @issues.detect {|i| !i.leaf?}) %></li>
    <% end -%>
    </ul>
  </li>
  <% end %>

<% if @can[:edit] %>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_start_date) %>:<%= @issue.start_date %></a>
    <ul>
      <li>
        <%= context_menu_link "start_date", bulk_update_issues_path(:ids => @issue_ids, :issue => {'start_date' => 'START_DATE'}, :back_url => @back), :method => :post, :disabled => (!@can[:edit] || @issues.detect {|i| !i.leaf?}), :id => 'start_date_link', :style => 'display:none;' %>
        <%= hidden_field_tag 'start_date', '' %><%= calendar_for('start_date') %>
      </li>
    </ul>
  </li>
  <%= javascript_tag do %>
    var start_date_url = document.getElementById('start_date_link').href;

    var onSelectStartDateFunc = function(dateText, inst) {
      var url = start_date_url.replace('START_DATE', dateText);
      document.getElementById('start_date_link').href = url;
      document.getElementById('start_date_link').click();
    }

    $(function() {
      $("#start_date").datepicker('option', 'onSelect', onSelectStartDateFunc);
    });
  <% end %>
<% else %>
  <li><%= l(:field_start_date) %>:<%= @issue.start_date %></li>
<% end %>

<% if @can[:edit] %>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_due_date) %>:<%= @issue.due_date %></a>
    <ul>
      <li>
        <%= context_menu_link "due_date", bulk_update_issues_path(:ids => @issue_ids, :issue => {'due_date' => 'DUE_DATE'}, :back_url => @back), :method => :post, :disabled => (!@can[:edit] || @issues.detect {|i| !i.leaf?}), :id => 'due_date_link', :style => 'display:none;' %>
        <%= hidden_field_tag 'due_date', '' %><%= calendar_for('due_date') %>
      </li>
    </ul>
  </li>
  <%= javascript_tag do %>
    var due_date_url = document.getElementById('due_date_link').href;

    var onSelectDueDateFunc = function(dateText, inst) {
      var url = due_date_url.replace('DUE_DATE', dateText);
      document.getElementById('due_date_link').href = url;
      document.getElementById('due_date_link').click();
    }

    $(function() {
      $("#due_date").datepicker('option', 'onSelect', onSelectDueDateFunc);
    });
  <% end %>
<% else %>
  <li><%= l(:field_start_date) %>:<%= @issue.start_date %></li>
<% end %>

  <% @options_by_custom_field.each do |field, options| %>
    <li class="folder cf_<%= field.id %>">
      <a href="#" class="submenu"><%= field.name %></a>
      <ul>
      <% options.each do |text, value| %>
        <li><%= bulk_update_custom_field_context_menu_link(field, text, value || text) %></li>
      <% end %>
      <% unless field.is_required? %>
        <li><%= bulk_update_custom_field_context_menu_link(field, l(:label_none), '__none__') %></li>
      <% end %>
      </ul>
    </li>
  <% end %>

  <%= call_hook(:view_issues_context_menu_end, {:issues => @issues, :can => @can, :back => @back }) %>
</ul>